# Generated by Django 5.1.15 on 2026-08-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255, unique=True)),
                ('raw_guid', models.CharField(max_length=500)),
                ('episode_number', models.PositiveIntegerField()),
                ('title_raw', models.TextField()),
                ('title_display', models.CharField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('link_url', models.URLField(max_length=500)),
                ('artwork_url', models.URLField(blank=True, max_length=500)),
                ('enclosure_url', models.URLField(blank=True, max_length=500)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
