# Generated by Django 5.1.15 on 2026-08-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('items_seen', models.PositiveIntegerField(default=0)),
                ('episodes_created', models.PositiveIntegerField(default=0)),
                ('episodes_updated', models.PositiveIntegerField(default=0)),
                ('items_below_floor', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='episode',
            name='feed_guest_hosts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
