# Generated by Django 5.1.15 on 2026-08-20 17:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('episodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_note', models.CharField(blank=True, max_length=500)),
                ('rateable_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='candidates.candidate')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='episodes.episode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('episode', 'candidate'), name='unique_episode_candidate')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateable_type', models.CharField(choices=[('demo', 'Demo'), ('appearance', 'Appearance')], max_length=20)),
                ('rateable_id', models.PositiveIntegerField()),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'rateable_type', 'rateable_id'), name='unique_user_rateable')],
            },
        ),
    ]
