# Generated by Django 5.1.15 on 2026-08-22 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_guest_names(apps, schema_editor):
    Appearance = apps.get_model("ratings", "Appearance")
    for appearance in Appearance.objects.select_related("candidate").all():
        if appearance.guest_name:
            continue
        if appearance.candidate_id:
            appearance.guest_name = appearance.candidate.stage_name
            appearance.save(update_fields=["guest_name"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_phase4_ratings'),
        ('episodes', '0002_feed_sync'),
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appearance',
            name='unique_episode_candidate',
        ),
        migrations.AddField(
            model_name='appearance',
            name='guest_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appearance',
            name='rating_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appearance',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appearance',
            name='smoothed_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appearances', to='candidates.candidate'),
        ),
        migrations.RunPython(fill_guest_names, noop),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rateable_type', 'rateable_id'], name='rating_rateable_idx'),
        ),
        migrations.AddConstraint(
            model_name='appearance',
            constraint=models.UniqueConstraint(condition=models.Q(('candidate__isnull', False)), fields=('episode', 'candidate'), name='unique_episode_candidate'),
        ),
        migrations.AddConstraint(
            model_name='appearance',
            constraint=models.UniqueConstraint(fields=('episode', 'guest_name'), name='unique_episode_guest_name'),
        ),
    ]
