# Generated by Django 5.1.15 on 2026-08-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('producer', 'Producer'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='producer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vote_eligible_override_at', models.DateTimeField(blank=True, null=True)),
                ('signup_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
