# Generated by Django 5.1.15 on 2026-08-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_phase3_auditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='appearance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='composite_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='demo_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='rating_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demo',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demo',
            name='smoothed_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
